#!/bin/bash
export N8N_INSTANCE_OWNER_MANAGED_BY_ENV=true
export N8N_INSTANCE_OWNER_EMAIL=admin@n8n.io
export N8N_INSTANCE_OWNER_PASSWORD_HASH='$2b$10$RHP5WMlZEcqLY.SG1tlg8.LSrPCD3UZAyuB01hrEYZiufGkBnBYTC'
n8n start --port=5678
